### ISSUE TITLE
downloaded files naming in builder

### ISSUE THREAD

**Issue by bouks** [openpsa/jsgrid#107]
The files should have the same naming convention.

Actual :
- jsgrid-0.1.0.min.css
- jsgrid-custom.js
- jsgrid-custom.min.js

Desired :

- jsgrid-0.1.0.min.css
- jsgrid-0.1.0-custom.js
- jsgrid-0.1.0-custom.min.js

**Comment by meh-uk** [comment]
I know this is fixed better in #115. But it is fixed, so closing.
