### ISSUE TITLE
column alignment off when using group headers

### ISSUE THREAD

**Issue by bchr02** [openpsa/jsgrid#119]
Grid column alignments are off when using group headers. The more columns the grid has the more apparent it is.

Demonstration here: http://www.tesllc.aero/temp/jqgrid3/

**Comment by bchr02** [comment]
Oops. On the demo site, I had the js code commented out that was needed to show the issue. Try looking at it now.

**Comment by flack** [comment]
Hi @bchr02! Sorry for the late reply, I've been quite busy in other projects, and it seems everybody else overlooked your ticket somehow :-(

Just to confirm, is this the issue you're referring to?

![cols](https://cloud.githubusercontent.com/assets/425166/6444047/548c3344-c0fb-11e4-9220-1646e32d1eea.png)

**Comment by bchr02** [comment]
@flack No worries. I understand. 

Actually, I am using Chrome web browser on MS Windows and this is what I am getting. And it only gets worst with the more columns that are added.
![image](https://cloud.githubusercontent.com/assets/10158167/6446176/2a70c878-c0d7-11e4-8be3-e78d189a2143.png)

You image shows the columns are off but not by as much.

**Comment by meh-uk** [comment]
Would the issue be fixed by setting the column width property differently?

**Comment by meh-uk** [comment]
By "column width" I mean the one that works out how wide the borders etc are so they can be corrected for. I've had to tweak that before to get it to look right when using custom css.

**Comment by bchr02** [comment]
are you referring to a css width property or a property in the api? Also, there is no custom css defined. Check out the source code. I only have:
````
<link rel="stylesheet" type="text/css" media="screen" href="bower_components/jquery-ui/themes/cupertino/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" media="screen" href="bower_components/jsgrid/dist/jsgrid-0.1.0.min.css">
````

**Comment by meh-uk** [comment]
I'm referring to the `scrollOffset` property - sorry I was in the car so I didn't have access to the source code.

We were using custom CSS, however thinking back I never did really understand why we picked the `scrollOffset` value we did - I suspect there is a quite legitimate bug here.

You should certainly be able to workaround the problem using `scrollOffset` though.

**Comment by meh-uk** [comment]
OK I've figured out the issue, and fixed it in pull #122.

**Comment by bchr02** [comment]
great. Thank you very much!

**Comment by meh-uk** [comment]
It's merged too, so lets close this.
