### ISSUE TITLE
jQuery UI Multiselect also requires localization files.

### ISSUE THREAD

**Issue by himiklab** [openpsa/jsgrid#33]
https://github.com/michael/multiselect/tree/master/js/locale

**Comment by flack** [comment]
Seeing how this plugin is not maintained any longer, we should consider replacing it altogether (see #4)

**Comment by OlegKi** [comment]
I don't specify the problem as a bug, especially as a jqGrid bug. **If one uses some plugin one should know it.** Moreover everybody can include in his code the lines like
```javascript
$.extend($.ui.multiselect.locale, {
	addAll:'Alle hinzufügen',
	removeAll:'Alle entfernen',
	itemsCount:'Einträge ausgewählt'
});
```
or just to use the code like
```javascript
$.ui.multiselect.locale.addAll = "Alle hinzufügen";
$.ui.multiselect.locale.removeAll = "Alle entfernen";
$.ui.multiselect.locale.itemsCount = "Einträge ausgewählt";
```

**Comment by meh-uk** [comment]
That doesn't sound like a great workaround to be honest.

**Comment by OlegKi** [comment]
I don't want to suggest any workaround. I said just that one should include locale file of jQuery UI Multiselect it one want us it for different language. It's in the same way like one should include jQuery UI Datepicker locale (see [here](https://github.com/jquery/jquery-ui/tree/master/ui/i18n)) if one need localized version of datepicker.
I wrote the code example just to show that if one don't find an exiting locale for the required language one can easy write it yourself.

**Comment by flack** [comment]
Well, the thing is, if we distribute a plugin, we should make some effort to include all parts of it. It is just annoying for users if they have to hunt for some missing files. Also, you have to be aware that the plugin's API might have changed, so if you use the bundled multiselect JS, there is no guarantee that the i18n files from current github master will work with it.

So I'd say we should include them. But preferably after we switch to a newer release of the plugin
