### ISSUE TITLE
Subgrid collapse doesn't work

### ISSUE THREAD

**Issue by flack** [openpsa/jsgrid#87]
See 

http://openpsa.github.io/grid.js/demos/kitchensink.html

you can load the subgrid, but it isn't removed when you close it. So when you open it again, it is displayed twice

**Comment by bouks** [comment]
Is it the same if there is datas in subgrids ?

**Comment by flack** [comment]
Haven't tried. But it works in Oleg's demo (on which I've based mine): http://www.ok-soft-gmbh.com/jqGrid/OK/grouping1.htm

**Comment by flack** [comment]
oops, just saw that this comes from here: https://github.com/openpsa/jsgrid/commit/4a1a83e14545bf78cc9ba3094e3846c4cf508e78. So my change has probably broken the fix. Version 2 will be forthcoming..

**Comment by flack** [comment]
Ok, should be fixed now. The problem was simply that the row ids in this particular example looked like `12.0`, this was then used to construct a jQuery selector looking like `#grid_12.0_expandedContent`, which of course is interpreted as "element with id `grid_12` and class `0_expandedContent`. So the string simply needed escaping
