### ISSUE TITLE
usage of key:true in colModel cause row selections to be wrong

### ISSUE THREAD

**Issue by bchr02** [openpsa/jsgrid#96]
@OlegKi fixed this issue in his repo. Here is the link:

https://github.com/OlegKi/jqGrid/commit/e1913ff3204b87d334ca0c4ac89e26b3fcf609cf

Maybe he would be willing to fix it here to?

**Comment by flack** [comment]
Thanks for the report! We can always try to pull changes from Oleg's repo, but AFAICT he refactored the readers quite a bit, so maybe this is only a fix for a problem introduced in his refactoring. Did you try with our js file, or do you have some example code to reproduce?

**Comment by bchr02** [comment]
Yes, I verified that the issue exists with your repo as well.

Here is a test site: https://www.tesllc.aero/temp/jqgrid/

**Comment by bchr02** [comment]
The issue occurs only when (key: true) and (subgrids: true).

**Comment by flack** [comment]
Alright, I've reproduced this now, cherry-picked Oleg's commit and verified that the issue is fixed. Thanks for the report!
